name: Release npm package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      # - run: npm run build --if-present
      # require the below to generate tsconfig.json
      - run: npm run dev:prepare
      - run: npm run lint
      - run: npm run prepack
      # - run: npm test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
